version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${LOCALSTACK_PORT_WEB_UI-8080}:${LOCALSTACK_PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES- }
      - DEBUG=${LOCALSTACK_DEBUG- }
      - DATA_DIR=${LOCALSTACK_DATA_DIR- }
      - PORT_WEB_UI=${LOCALSTACK_PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LOCALSTACK_LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${LOCALSTACK_KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  marketstore:
    build:
      context: ./src/marketstore
    container_name: marketstore.local
    image: alpacamarkets/marketstore:latest
    ports:
      - "5993:5993"
      - "5995:5995"
    restart: always
    networks:
      finbots:
    volumes:
      - ./mkts.yml:/etc/mkts.yml
      - ./.volumes/marketstore:/data

networks:
  finbots:
    name: finbots_dev
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
