apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: finbotsdev-

build:
  artifacts:
    - image: alpacamarkets/marketstore
      context: ./src/finbotsdev/marketstore/
    - image: fb-persists
      context: ./src/finbotsdev/fb_persists/

deploy:
  helm:
    releases:
      - name: postgres
        remoteChart: bitnami/postgresql
      - name: localstack
        remoteChart: localstack/localstack

  kubectl:
    manifests:
      - ./src/finbotsdev/fb_persists/kubernetes.yaml
