apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: finbotsdev-

build:
  artifacts:
    - image: alpacamarkets/marketstore
      context: ./src/finbotsdev/marketstore/
    - image: fb-persists
      context: ./src/finbotsdev/fb_persists/

deploy:
  # https://skaffold.dev/docs/pipeline-stages/deployers/helm/
  helm:
    releases:
      - name: db
        remoteChart: bitnami/postgresql
      - name: aws
        remoteChart: localstack/localstack
      - name: marketstore
        chartPath: ./src/finbotsdev/marketstore/helm-chart

  # https://skaffold.dev/docs/pipeline-stages/deployers/kubectl/
  kubectl:
    manifests:
      - ./src/finbotsdev/fb_persists/kubernetes.yaml

  # https://skaffold.dev/docs/pipeline-stages/deployers/kustomize/
  kustomize: {}
