apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: finbotsdev-

build:
  artifacts:
    - image: alpacamarkets/marketstore
      context: ./src/marketstore/
    - image: fb-persists
      context: ./src/fb-persists/

deploy:
  helm:
    releases:
      - name: marketstore
        chartPath: ./src/marketstore/helm-chart
  kubectl:
    manifests:
      - ./src/fb-persists/kubernetes.yaml
